version: 0.2

env:
  parameter-store:
    PUBLIC_KEY: "/calc/PRIVATE_KEY"
    EC2_IP_ADDRESS: "/calc/EC2_IP_ADDRESS"

phases:
  install:
    runtime-versions:
      nodejs: 16.x
  pre_build:
    commands:
      - echo $PUBLIC_KEY > pk.pem
      - chmod 400 pk.pem
  build:
    commands:
      - npm install --production
  post_build:
    commands:
      - cat pk.pem
      - ssh-keyscan -t rsa $EC2_IP_ADDRESS >> ~/.ssh/known_hosts
      - scp -i ./pk.pem -r * ec2-user@$EC2_IP_ADDRESS:~
