version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
  pre_build:
    commands:

  build:
    commands:
      - npm install --production
  post_build:
    commands:
      - zip -r lam2js index.js node_modules
      - aws lambda update-function-code --function-name lam2js --zip-file fileb://lam2js.zip
